### ISSUE TITLE
ilimanager –createIliModels creates unusable iliModels.xml in local repository

### ISSUE THREAD

**Issue by behrm** [claeis/ilimanager#14]
First with ilimanager/0.9.2-SNAPSHOT/ilimanager-0.9.2-20230530.085221-4 create two local repositories:

`java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --cloneIliRepos --proxy ***** --proxyPort 8080 --out D:\Interlis_Repositories --repos https://models.interlis.ch/`

`java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --cloneIliRepos --proxy ***** --proxyPort 8080 --out D:\Interlis_Repositories –-repos https://models.geo.sg.ch`

Then create two iliModels.xml:

`java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --createIliModels --proxy ***** --proxyPort 8080 --out D:\Interlis_Repositories\models.interlis.ch\ilimodels.xml  --repos D:\Interlis_Repositories\models.interlis.ch`

`java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --createIliModels --proxy ***** --proxyPort 8080 --out D:\Interlis_Repositories\models.geo.sg.ch\ilimodels.xml  --repos D:\Interlis_Repositories\models.geo.sg.ch`

Then in FME-Workbench adding a Interlis-Reader with parameter Models Directory "D:\Interlis_Repositories\models.interlis.ch;D:\Interlis_Repositories\models.geo.sg.ch" (and XTF-File) ili2fme fails with Error:

```
ili2fme-7.2.0-ed9cf94b1802a8ccbeaf3b77914108916795fd42
ili2c-5.3.2-6fb5df2877070aeb16c7b39a206a61e2518682c8
iox-ili-1.21.15-f055cd0e781e5b2754c475ec4573eb3bed12bd8b
java.version 1.8.0_265
maxMemory 2796544 KB
ili2fme reader uses enhanced geometry handling
checkUniqueOid <false>
metaConfig <>
validate <true>
validationConfig <>
validateMultiplicity <true>
ili1IgnorePolygonBuildingErrors <false>
trimValues <true>
geometryEncoding <FMEBIN>
geoAttrMapping <EncodeAsFmeAttribute>
ili1RenumberTid <false>
lineTables <Polygon>
inheritanceMapping <SuperClass>
createEnumTypes <No>
ili1AddDefVal <false>
ili1EnumAsItfCode <false>
xtfFile <D:\SG_Gewaessernetz_kt_V1_0_0.xtf>
modeldir <D:\Interlis_Repositories\models.interlis.ch;D:\Interlis_Repositories\models.geo.sg.ch>
httpProxyHost <*****>
httpProxyPort <8080>
modelVersion from xtf <2.3>
model from xtf <Units>
model from xtf <CoordSys>
model from xtf <SG_Basis_kt_V1_0_0>
model from xtf <SG_Gewaessernetz_kt_V1_0_0>
lookup model <Units> 2.3 in repository <D:\Interlis_Repositories\models.interlis.ch/>
model RoadsExdm2ien: no version without precursor; model ignored
model DatasetIdx16: no version without precursor; model ignored
model IliRepository20: no version without precursor; model ignored
model Time: no version without precursor; model ignored
model Time: no version without precursor; model ignored
model IliRepository09: no version without precursor; model ignored
model CoordSys: no version without precursor; model ignored
model CoordSys: no version without precursor; model ignored
model RoadsExdm2ien_10: no version without precursor; model ignored
model IlisMeta07: no version without precursor; model ignored
model Units: no version without precursor; model ignored
model Units: no version without precursor; model ignored
model IlisMeta16: no version without precursor; model ignored
model StandardSymbology: no version without precursor; model ignored
model StandardSymbology: no version without precursor; model ignored
model AbstractSymbology: no version without precursor; model ignored
model AbstractSymbology: no version without precursor; model ignored
lookup model <Units> 2.3 in repository <D:\Interlis_Repositories\models.geo.sg.ch/>
lookup model <CoordSys> 2.3 in repository <D:\Interlis_Repositories\models.interlis.ch/>
lookup model <CoordSys> 2.3 in repository <D:\Interlis_Repositories\models.geo.sg.ch/>
lookup model <SG_Basis_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories\models.interlis.ch/>
lookup model <SG_Basis_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories\models.geo.sg.ch/>
lookup model <SG_Gewaessernetz_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories\models.interlis.ch/>
lookup model <SG_Gewaessernetz_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories\models.geo.sg.ch/>
Units, CoordSys: model(s) not found
ch.interlis.ili2c.Ili2cException: Units, CoordSys: model(s) not found
	at ch.interlis.ilirepository.IliManager.getConfig(IliManager.java:339)
	at ch.interlis.ili2fme.Ili2Reader.myopen(Ili2Reader.java:564)
	at ch.interlis.ili2fme.Ili2Reader.open(Ili2Reader.java:140)
ch.interlis.ili2c.Ili2cException: Units, CoordSys: model(s) not found
Failed to obtain any schemas from reader 'ch.ehi.fme.Main' from 1 datasets. This may be due to invalid datasets or format accessibility issues due to licensing, dependencies, or module loading. See logfile for more information
FME Session Duration: 0.6 seconds. (CPU: 0.6s user, 0.2s system)
END - ProcessID: 18632, peak process memory usage: 410704 kB, current process memory usage: 410704 kB
Failed to obtain any schemas from reader 'ch.ehi.fme.Main' from 1 datasets. This may be due to invalid datasets or format accessibility issues due to licensing, dependencies, or module loading. See logfile for more information
Program Terminating
Translation FAILED.
```
Then after overwriting the file D:\Interlis_Repositories\models.interlis.ch\ilimodels.xml with the content of file https://models.interlis.ch/ilimodels.xml the creation of the Interlis-Reader in FME-Workbench is succesfull:

```
ili2fme-7.2.0-ed9cf94b1802a8ccbeaf3b77914108916795fd42
ili2c-5.3.2-6fb5df2877070aeb16c7b39a206a61e2518682c8
iox-ili-1.21.15-f055cd0e781e5b2754c475ec4573eb3bed12bd8b
java.version 1.8.0_265
maxMemory 2796544 KB
ili2fme reader uses enhanced geometry handling
checkUniqueOid <false>
metaConfig <>
validate <true>
validationConfig <>
validateMultiplicity <true>
ili1IgnorePolygonBuildingErrors <false>
trimValues <true>
geometryEncoding <FMEBIN>
geoAttrMapping <EncodeAsFmeAttribute>
ili1RenumberTid <false>
lineTables <Polygon>
inheritanceMapping <SuperClass>
createEnumTypes <No>
ili1AddDefVal <false>
ili1EnumAsItfCode <false>
xtfFile <D:\SG_Gewaessernetz_kt_V1_0_0.xtf>
modeldir <D:\Interlis_Repositories\models.interlis.ch;D:\Interlis_Repositories\models.geo.sg.ch>
httpProxyHost <*****>
httpProxyPort <8080>
modelVersion from xtf <2.3>
model from xtf <Units>
model from xtf <CoordSys>
model from xtf <SG_Basis_kt_V1_0_0>
model from xtf <SG_Gewaessernetz_kt_V1_0_0>
lookup model <Units> 2.3 in repository <D:\Interlis_Repositories\models.interlis.ch/>
lookup model <CoordSys> 2.3 in repository <D:\Interlis_Repositories\models.interlis.ch/>
lookup model <SG_Basis_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories\models.interlis.ch/>
lookup model <SG_Basis_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories\models.geo.sg.ch/>
lookup model <SG_Gewaessernetz_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories\models.interlis.ch/>
lookup model <SG_Gewaessernetz_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories\models.geo.sg.ch/>
ilifile <D:\Interlis_Repositories\models.interlis.ch\refhb23\CoordSys-20151124.ili>
ilifile <D:\Interlis_Repositories\models.interlis.ch\refhb23\Units-20120220.ili>
ilifile <D:\Interlis_Repositories\models.geo.sg.ch\Basis\SG_Basis_kt_V1_0_0.ili>
ilifile <D:\Interlis_Repositories\models.geo.sg.ch\2_Natur_und_Umwelt\I_Gewaesser\SG_Gewaessernetz_kt_V1_0_0.ili>
Merged 23 schema features read from 1 datasets into 23 resulting feature types
Opened mapping File C:\Users\*****~1\AppData\Local\Temp\5\FME_1687873783038_11956.fmw for output
Mapping File Generation was SUCCESSFUL
Mapping File Generation was SUCCESSFUL
FME Session Duration: 1.1 seconds. (CPU: 0.9s user, 0.4s system)
END - ProcessID: 16268, peak process memory usage: 426768 kB, current process memory usage: 425140 kB
```

Please, what is the explanation of this phenomenon?

**Comment by edigonzales** [comment]
Why the second ilimanager runs? `--cloneIliRepos` creates already an ilimodels.xml file.

**Comment by behrm** [comment]
Stefan thank You for your reply.

So I remove directories D:\Interlis_Repositories\ and c:\users\%username%\.ilicache

Again I clone **two** repositories  consecutively:

`java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --cloneIliRepos --proxy ******* --proxyPort 8080 --out D:\Interlis_Repositories --repos  https://models.geo.sg.ch
`
`java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --cloneIliRepos --proxy ******* --proxyPort 8080 --out D:\Interlis_Repositories --repos https://models.interlis.ch`

I verify D:\Interlis_Repositories\ilimodels.xml has been created.

Adding the Interlis-Reader in in FME-Workbench with "Model Directory" parameter D:\Interlis_Repositories fails again.

```
ili2fme-7.2.0-ed9cf94b1802a8ccbeaf3b77914108916795fd42
ili2c-5.3.2-6fb5df2877070aeb16c7b39a206a61e2518682c8
iox-ili-1.21.15-f055cd0e781e5b2754c475ec4573eb3bed12bd8b
java.version 1.8.0_265
maxMemory 2796544 KB
ili2fme reader uses enhanced geometry handling
checkUniqueOid <false>
metaConfig <>
validate <true>
validationConfig <>
validateMultiplicity <true>
ili1IgnorePolygonBuildingErrors <false>
trimValues <true>
geometryEncoding <FMEBIN>
geoAttrMapping <EncodeAsFmeAttribute>
ili1RenumberTid <false>
lineTables <Polygon>
inheritanceMapping <SuperClass>
createEnumTypes <No>
ili1AddDefVal <false>
ili1EnumAsItfCode <false>
xtfFile <O:\Freigabe\AWE\GN10\Primaerdaten\SG_Gewaessernetz_kt_V1_0_0.xtf>
modeldir <D:\Interlis_Repositories>
modelVersion from xtf <2.3>
model from xtf <Units>
model from xtf <CoordSys>
model from xtf <SG_Basis_kt_V1_0_0>
model from xtf <SG_Gewaessernetz_kt_V1_0_0>
lookup model <Units> 2.3 in repository <D:\Interlis_Repositories/>
lookup model <CoordSys> 2.3 in repository <D:\Interlis_Repositories/>
lookup model <SG_Basis_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories/>
lookup model <SG_Gewaessernetz_kt_V1_0_0> 2.3 in repository <D:\Interlis_Repositories/>
SG_Basis_kt_V1_0_0, SG_Gewaessernetz_kt_V1_0_0: model(s) not found
ch.interlis.ili2c.Ili2cException: SG_Basis_kt_V1_0_0, SG_Gewaessernetz_kt_V1_0_0: model(s) not found
	at ch.interlis.ilirepository.IliManager.getConfig(IliManager.java:339)
	at ch.interlis.ili2fme.Ili2Reader.myopen(Ili2Reader.java:564)
	at ch.interlis.ili2fme.Ili2Reader.open(Ili2Reader.java:140)
ch.interlis.ili2c.Ili2cException: SG_Basis_kt_V1_0_0, SG_Gewaessernetz_kt_V1_0_0: model(s) not found
Failed to obtain any schemas from reader 'ch.ehi.fme.Main' from 1 datasets. This may be due to invalid datasets or format accessibility issues due to licensing, dependencies, or module loading. See logfile for more information
FME Session Duration: 0.7 seconds. (CPU: 0.7s user, 0.2s system)
END - ProcessID: 16788, peak process memory usage: 410884 kB, current process memory usage: 410884 kB
Failed to obtain any schemas from reader 'ch.ehi.fme.Main' from 1 datasets. This may be due to invalid datasets or format accessibility issues due to licensing, dependencies, or module loading. See logfile for more information
Program Terminating
Translation FAILED.
```
**Since ili2fme complains about missing the first cloned repository, I conclude the ilimodels.xml has not been updated for the second clone operation but erroneously overwritten,**

**Comment by beistehen** [comment]
(Bezug nehmend auf den originalen Post)

Es scheint hier noch mehrere Baustellen zu geben:

1. Offenbar klont `--cloneIliRepos` nicht vollständig, zumindest nicht im Fall models.interlis.ch.
Auf models.interlis.ch gibt es ein (verstecktes) Verzeichnis namens [/obsolete](https://models.interlis.ch/obsolete/). Dieses Verzeichnis wird beim Klonen nicht mitkopiert und fehlt nun im Ziel. Beim Klonprozess wird, wie von @edigonzales bemerkt, ein neues `ilimodels.xml` angelegt. Dieses enthält jedoch nur Verweise auf Modelle, die es im frisch geklonten Repository auch vorfindet.
2. Das im Ziel neu angelegte `ilimodels.xml` enthält Informationen, welche in den jeweiligen Modellen als Metadaten enthalten sind. Im FME-Log taucht die Meldung `no version without precursor; model ignored` auf. Diese rührt daher, das im Kopfteil des beanstandeten Modells (z. B. _Units_) das Metaattribut _!!@precursorVersion_ erfasst ist: `!!@precursorVersion = 2005-06-06`. Im (neu erzeugten) `ilimodels.xml` ist jedoch kein Eintrag für dieses Vorgängermodell erfasst, weshalb er nicht gefunden werden kann und schlussendlich das Modell (in diesem Beispiel _Units_) komplett ignoriert wird. Also gilt es als nicht vorhanden, was wiederum zum Abbruch des FME-Prozesses führt (`Units, CoordSys: model(s) not found`)
3. (weniger relevant, aber ärgerlich: Das `ilimodels.xml` von models.interlis.ch wird händisch gepflegt. Eine Folge davon ist, dass die im Modell _Units_ angegebene _precursorVersion_ nicht mit derjenigen in `ilimodels.xml` übereinstimmt. Eine solche Prüfung scheint es bisher nicht zu geben.)

#### Weshalb funktioniert es dann mit dem originalen ilimodels.xml von models.interlis.ch?
Weil es dort einen Eintrag für das Vorgängermodell gibt:
```xml
<IliRepository09.RepositoryIndex.ModelMetadata TID="20">
  <Name>Units</Name>
  <SchemaLanguage>ili2_3</SchemaLanguage>
  <File>obsolete/Units-20120220_o0.ili</File>
  <Version>2005-06-16</Version>
  <Issuer>http://www.interlis.ch/models</Issuer>
  <technicalContact>mailto:info@interlis.ch</technicalContact>
  <furtherInformation>https://www.interlis.ch</furtherInformation>
  <md5>66ad28cb2d65ffacdee360c6f4f6cb69</md5>
</IliRepository09.RepositoryIndex.ModelMetadata>
```

Dieser Eintrag verweist zwar auf eine Datei im Verzeichnis `/obsolete`, welches es im geklonten Repository gar nicht gibt, aber das scheint hier nicht geprüft zu werden. Wichtig ist, dass der Eintrag über \<Version>2005-06-16\</Version> (sic!, siehe Puntk 3 oben) gefunden wird.

#### Wie Abhilfe schaffen?
Dies scheint m. E. nur händisch möglich zu sein, indem man den \<precursorVersion>-Eintrag aus der lokalen Version von `ilimodels.xml` entfernt (zumindest für die am häufigsten referenzierten Modelle wie _Units_, _CoordSys_).

**Comment by behrm** [comment]
> (Bezug nehmend auf den originalen Post)
> 
> Es scheint hier noch mehrere Baustellen zu geben:
> 
> 1. Offenbar klont `--cloneIliRepos` nicht vollständig, zumindest nicht im Fall models.interlis.ch.
>    Auf models.interlis.ch gibt es ein (verstecktes) Verzeichnis namens [/obsolete](https://models.interlis.ch/obsolete/). Dieses Verzeichnis wird beim Klonen nicht mitkopiert und fehlt nun im Ziel. Beim Klonprozess wird, wie von @edigonzales bemerkt, ein neues `ilimodels.xml` angelegt. Dieses enthält jedoch nur Verweise auf Modelle, die es im frisch geklonten Repository auch vorfindet.
> 2. Das im Ziel neu angelegte `ilimodels.xml` enthält Informationen, welche in den jeweiligen Modellen als Metadaten enthalten sind. Im FME-Log taucht die Meldung `no version without precursor; model ignored` auf. Diese rührt daher, das im Kopfteil des beanstandeten Modells (z. B. _Units_) das Metaattribut _!!@precursorVersion_ erfasst ist: `!!@precursorVersion = 2005-06-06`. Im (neu erzeugten) `ilimodels.xml` ist jedoch kein Eintrag für dieses Vorgängermodell erfasst, weshalb er nicht gefunden werden kann und schlussendlich das Modell (in diesem Beispiel _Units_) komplett ignoriert wird. Also gilt es als nicht vorhanden, was wiederum zum Abbruch des FME-Prozesses führt (`Units, CoordSys: model(s) not found`)
> 3. (weniger relevant, aber ärgerlich: Das `ilimodels.xml` von models.interlis.ch wird händisch gepflegt. Eine Folge davon ist, dass die im Modell _Units_ angegebene _precursorVersion_ nicht mit derjenigen in `ilimodels.xml` übereinstimmt. Eine solche Prüfung scheint es bisher nicht zu geben.)
> 
> #### Weshalb funktioniert es dann mit dem originalen ilimodels.xml von models.interlis.ch?
> Weil es dort einen Eintrag für das Vorgängermodell gibt:
> 
> ```
> <IliRepository09.RepositoryIndex.ModelMetadata TID="20">
>   <Name>Units</Name>
>   <SchemaLanguage>ili2_3</SchemaLanguage>
>   <File>obsolete/Units-20120220_o0.ili</File>
>   <Version>2005-06-16</Version>
>   <Issuer>http://www.interlis.ch/models</Issuer>
>   <technicalContact>mailto:info@interlis.ch</technicalContact>
>   <furtherInformation>https://www.interlis.ch</furtherInformation>
>   <md5>66ad28cb2d65ffacdee360c6f4f6cb69</md5>
> </IliRepository09.RepositoryIndex.ModelMetadata>
> ```
> 
> Dieser Eintrag verweist zwar auf eine Datei im Verzeichnis `/obsolete`, welches es im geklonten Repository gar nicht gibt, aber das scheint hier nicht geprüft zu werden. Wichtig ist, dass der Eintrag über <Version>2005-06-16</Version> (sic!, siehe Puntk 3 oben) gefunden wird.
> 
> #### Wie Abhilfe schaffen?
> Dies scheint m. E. nur händisch möglich zu sein, indem man den <precursorVersion>-Eintrag aus der lokalen Version von `ilimodels.xml` entfernt (zumindest für die am häufigsten referenzierten Modelle wie _Units_, _CoordSys_).



> `https://models.geo.sg.ch`

Wenn das lokale Verzeichnis .ilichache mit ili2fme durch Zugriff auf "https://models.interlis.ch;https://models.geo.sg.ch" initialisiert wird, enthält es zwei ilimodels.xml Dateien. 

In einem zweiten Schritt mit ili2fme und dem Parameter Models Directory C:\Users\%username%\.ilicache\models.interlis.ch;C:\Users\%username%\.ilicache\models.geo.sg.ch
arbeitet ili2fme ohne Fehler. In diesem Szenario funktioniert das "klonieren" (auch mit  <precursorVersion>-Einträgen im ilimodels.xml).

**Comment by edigonzales** [comment]
`--cloneIliRepos` kopiert bewusst nur die aktuellen Modelle. Bin auch mal darüber gestolpert.

**Comment by beistehen** [comment]
> In diesem Szenario funktioniert das "klonieren" (auch mit -Einträgen im ilimodels.xml).

Spannende Beobachtung! Wie es scheint, sind die Daten in .ilicache nicht via die Funktionalität `--cloneIliRepos` geklont, sondern 1:1 kopiert. Das sieht man daran, dass der Inhalt von `ilimodels.xml` identisch ist mit dem Inhalt auf models.interlis.ch. Also ist auch die Geschichte mit der \<precursorVersion> gelöst und valide.

Dies ist aber ein anderes Szenario, als was du eingangs beschrieben hast: Da wolltest du zwei komplett losgelöste Repos erstellen und diese in FME referenzieren.

**Comment by behrm** [comment]
> > In diesem Szenario funktioniert das "klonieren" (auch mit -Einträgen im ilimodels.xml).
> 
> Spannende Beobachtung! Wie es scheint, sind die Daten in .ilicache nicht via die Funktionalität `--cloneIliRepos` geklont, sondern 1:1 kopiert. Das sieht man daran, dass der Inhalt von `ilimodels.xml` identisch ist mit dem Inhalt auf models.interlis.ch. Also ist auch die Geschichte mit der <precursorVersion> gelöst und valide.
> 
> Dies ist aber ein anderes Szenario, als was du eingangs beschrieben hast: Da wolltest du zwei komplett losgelöste Repos erstellen und diese in FME referenzieren.

Ja das ist ein anderes Szenario. Vielen Dank für deinen Beitrag.

**Comment by claeis** [comment]
> First with ilimanager/0.9.2-SNAPSHOT/ilimanager-0.9.2-20230530.085221-4 create two local repositories:
> 
> `java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --cloneIliRepos --proxy ***** --proxyPort 8080 --out D:\Interlis_Repositories --repos https://models.interlis.ch/`
> 
> `java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --cloneIliRepos --proxy ***** --proxyPort 8080 --out D:\Interlis_Repositories –-repos https://models.geo.sg.ch`

In Bezug auf die Original-Frage: das Problem sind diese beiden Aufrufe. Zweimal das selbe ``--out`` Verzeichnis führt dazu, das der zweite Aufruf das Resultat vom ersten Aufruf überschreibt. Man muss also für jeden Aufruf ein neues/anderes Zielverzeichnis angeben. Das nachfolgende ``--createIliModels`` ist nicht notwendig/schädlich, da ``--cloneIliRepos`` das ilimodels.xml (hergeleitet aus den Quell-ilimodels.xml) bereits erstellt (das ist somit vollständiger als aus den ili-Dateien neu erzeugen).

**Comment by behrm** [comment]
> > First with ilimanager/0.9.2-SNAPSHOT/ilimanager-0.9.2-20230530.085221-4 create two local repositories:
> > `java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --cloneIliRepos --proxy ***** --proxyPort 8080 --out D:\Interlis_Repositories --repos https://models.interlis.ch/`
> > `java -jar d:\tmp\ilimanager-0.9.2-SNAPSHOT.jar --cloneIliRepos --proxy ***** --proxyPort 8080 --out D:\Interlis_Repositories –-repos https://models.geo.sg.ch`
> 
> In Bezug auf die Original-Frage: das Problem sind diese beiden Aufrufe. Zweimal das selbe `--out` Verzeichnis führt dazu, das der zweite Aufruf das Resultat vom ersten Aufruf überschreibt. Man muss also für jeden Aufruf ein neues/anderes Zielverzeichnis angeben. Das nachfolgende `--createIliModels` ist nicht notwendig/schädlich, da `--cloneIliRepos` das ilimodels.xml (hergeleitet aus den Quell-ilimodels.xml) bereits erstellt (das ist somit vollständiger als aus den ili-Dateien neu erzeugen).

Vielen Dank, wenn die Klone jeweils in einem eigenen Verzeichnis erzeugt werden. funktioniert es.

**Comment by behrm** [comment]
> In Bezug auf die Original-Frage: das Problem sind diese beiden Aufrufe. Zweimal das selbe `--out` Verzeichnis führt dazu, das der zweite Aufruf das Resultat vom ersten Aufruf überschreibt. Man muss also für jeden Aufruf ein neues/anderes Zielverzeichnis angeben. Das nachfolgende `--createIliModels` ist nicht notwendig/schädlich, da `--cloneIliRepos` das ilimodels.xml (hergeleitet aus den Quell-ilimodels.xml) bereits erstellt (das ist somit vollständiger als aus den ili-Dateien neu erzeugen).

Die Motivation zum hier geschilderten Vorgehen resp. Test mit ilimanager ist ein Anwendungsfall, in dem verschiedene Interlis basierte Verarbeitungen (ili2fme, ili2db, ilivalidator) auf einen programmatisch vorbereiteten lokalen Interlis-Cache (strukturell vergleichbar mit dem Verzeichnis .ilichache) lesend zugreifen.

**Comment by edigonzales** [comment]
> Die Motivation zum hier geschilderten Vorgehen resp. Test mit ilimanager ist ein Anwendungsfall, in dem verschiedene Interlis basierte Verarbeitungen (ili2fme, ili2db, ilivalidator) auf einen programmatisch vorbereiteten lokalen Interlis-Cache (strukturell vergleichbar mit dem Verzeichnis .ilichache) lesend zugreifen.

Ah ja, das wollte ich eigentlich auch mal. Also den .ilicache manuell befüllen, um offline-fähig zu sein und _nicht_ explizit andere "modeldirs" anzugeben. Bin aber nicht sicher, ob das so geht, weil ich das Verhalten des Caches nicht ganz verstehe (also wann greift er genau? wann nicht?).

**Comment by claeis** [comment]
Den ``.ilicache`` sollte man nicht manuell befüllen. Das ist etwas Internes des ili2c.

Aber eine lokale Kopie der Modelle kann Sinn machen; darum die Funktion ``--cloneIliRepos``
