### ISSUE TITLE
ilimanager --cloneIliRepos - Frage zum klonieren von XML-Codelisten Dateien

### ISSUE THREAD

**Issue by behrm** [claeis/ilimanager#15]
"ilimanager --cloneIliRepos" kloniert bisher keine der in verschiedenen Repositories vorhandenen " XML-Codelisten Dateien".
Sind in diesem Kontext zukünftig funktionelle Erweiterungen zu erwarten?

**Comment by claeis** [comment]
Das ist machbar, aber aktuell nicht geplant/nicht finanziert.

**Comment by behrm** [comment]
danke
