### ISSUE TITLE
--updateIliData throws exeption

### ISSUE THREAD

**Issue by romefi** [claeis/ilimanager#3]
First: Awesome tool! You have to love it!

`--createIliData` works, `--updateIliData` throws exeption:

```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at ch.ehi.ilimanager.Main.main(Main.java:188)
```
Tested on Windows with [modelrepository.zip](https://github.com/claeis/ilimanager/files/9980789/modelrepository.zip)

**Comment by claeis** [comment]
Welche Kommandozeile? (fehlt evtl. --out neuesIliData.xml?)

**Comment by romefi** [comment]
Hatte die Parameter --datasetId und --data vergessen, entschuldige. Jetzt funktioniert es.
