### ISSUE TITLE
wrong content in <Version>

### ISSUE THREAD

**Issue by imhofdaniel** [claeis/ilimanager#4]
The version tag <Version> contains always the timestamp of the file and not the VERSION-statement of the ili-file.

ili-File:
VERSION "2022-05-30"  =

ilimodels.xml:
<Version>2022-11-10</Version>

With MakeIliModelsXml from ili2c it worked correctly.

**Comment by claeis** [comment]
- Welche ili-Datei?
- Weclhe ili2c-Version?

**Comment by beistehen** [comment]
Funktioniert bei mir korrekt für Modelle in INTERLIS 2.3 und Option `--createIliModels`.

* Wie sieht deine Befehlszeile aus?
* Ili1 oder Ili2_3-Modelle?

Hinweis: MakeIliModelsXml nutzt das [Repository09-Modell](https://models.interlis.ch/core/IliRepository09-20120220.ili), ilimanager unterstützt meines Wissens nur das neue [Repository20-Modell](https://models.interlis.ch/core/IliRepository20.ili).

**Comment by imhofdaniel** [comment]
ilimanager-0.9.0:
java -jar ilimanager-0.9.0.jar --createIliModels --out newIliModels.xml --repos models

ili2c-5.3.0:
java -cp ili2c.jar ch.interlis.ili2c.MakeIliModelsXml2 models

[ilimodels_ili2c-5.3.0.xml.txt](https://github.com/claeis/ilimanager/files/9989785/ilimodels_ili2c-5.3.0.xml.txt)
[ilimodels-ilimanager-0.9.0.xml.txt](https://github.com/claeis/ilimanager/files/9990031/ilimodels-ilimanager-0.9.0.xml.txt)
[Baulinien_V320.ili.txt](https://github.com/claeis/ilimanager/files/9990052/Baulinien_V320.ili.txt)

**Comment by beistehen** [comment]
siehe https://github.com/claeis/ilimanager/issues/5#issuecomment-1312701667
